---
title: "Conceptual Questions"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

## Task 1: Conceptual Questions

-   If your working directory is **myfolder/homework/**, what *relative* path would you specify to get the file located at **myfolder/MyData.csv**?

> ../MyData.csv

-   What are the major benefits of using R projects?

> R projects keep all of the files related to a specific project organized in a centralized folder/working directory. Additionally, it automatically creates most of the necessary documents and folders (especially if you are cloning a git repository). R projects also sets the working directory when you open a document inside the project

-   What is git and what is github?

> GitHub is a server for git. Github is one of the most popular online hosting sites for git. It also has features that allows you to collaborate with others. Git is a version control software. That is, it remembers past versions of your code at each commit and allows you to revert back to them. You can also create branches that allow you to work on a project without messing up the code that can merge back to the main branch.

-   What are the two main differences between a **tibble** and a **data.frame**?

> Tibble is a special type of dataframe made specifically for the tidyverse. "Tibbles are data.frames that are lazy and surly". They defaut to printing only the first few rows and columns. They are also stricter, making you write better, cleaner code.

-   Rewrite the following nested function call using **BaseR**'s chaining operator:

```
arrange(filter(select(as_tibble(iris), starts_with("Petal"), Species), Petal.Length < 1.55), Species)
```

> iris |>  
    as_tibble() |> 
    select(starts_with("Petal"), Species) |>
    filter(Petal.Length < 1.55) |>
    arrange(Species)
